baseURL: "notesonidleness.github.io"
title: Laataiasu
paginate: 10
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: G-TV5901EQN9

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Laataiasu
  description: "Notes on Idleness"
  keywords: [laataiasu, chanculus, notes on idleness, god of idleness]
  author: chanculus
  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false
  hideSummary: true

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "favicon.ico"
    favicon16x16: "favicon-16x16.png"
    favicon32x32: "favicon-32x32.png"
    apple_touch_icon: "apple-touch-icon.png"
    safari_pinned_tab: "safari-pinned-tab.svg"

  label:
    text: "Home"
    icon: /apple-touch-icon.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: Laataiasu
    subtitle: "Notes on Idleness"
    imageUrl: "https://catatankemalasan.files.wordpress.com/2021/11/photo.jpg"
    imageWidth: 200
    imageHeight: 200
    imageTitle: laataiasu
    buttons:
      # - name: Writings
      #   url: post
      # - name: Tags
      #   url: tags

  # home-info mode
  homeInfoParams:
    Title: "Laataiasu 💦" # "Hi there \U0001F44B"
    Content: "Notes on Idleness"

  socialIcons:
    - name: twitter
      url: "https://twitter.com/cecakhalal"
    # - name: stackoverflow
    #   url: "https://stackoverflow.com"
    - name: instagram
      url: "https://instagram.com/notesonidleness"
    - name: github
      url: "https://github.com/ichsanulamal"
    - name: linktree
      url: "https://linktr.ee/ichsanulamal"

  analytics:
    google:
      SiteVerificationTag: "lNHHQDjBfYsTAIsrTA30JCemupM27YF71k1E6MO2AFI"
    bing:
      SiteVerificationTag: "CADE8DE57C8D148188B761178BD81544"
    yandex:
      SiteVerificationTag: "701081e031c5a7d2"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  # editPost:
  #   URL: "https://github.com/<path_to_repo>/content"
  #   Text: "Suggest Changes" # edit text
  #   appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    # - identifier: Writings
    #   name: Writings
    #   url: /post/
    #   weight: 1
    - identifier: Posts
      name: Posts
      url: /archives/
      weight: 1
    - identifier: Tags
      name: Tags
      url: /tags/
      weight: 2
    - identifier: Search
      name: Search
      url: /search/
      weight: 4
    - identifier: About
      name: About
      url: /about/
      weight: 5
    # - identifier: example
    #   name: example.org
    #   url: https://example.org
    #   weight: 4
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary
